#!/usr/bin/env bash
#
# Build the fixes bundle that a launcher downloads: everything needed to apply
# a per-game fix, and nothing else.
#
#     runtime/make-fixes-bundle.sh [output directory]
#
# WHAT GOES IN, AND WHY IT IS DERIVED
#
# The file list is read from the installers themselves rather than written
# here. Each install-*.sh resolves its carrier DLL and the export reader
# through HERE="$(dirname "$0")", so what it needs is exactly what it names --
# and a hand-written list is the second copy that goes stale the first time a
# title is added. The same reasoning produces manifest.json: which DLL belongs
# to which game, which carrier it rides, under what name the original is kept,
# and whether the fix needs a registry override, all read out of the scripts.
#
# EVERYTHING IS FLAT. The installers resolve siblings with $HERE, so a bundle
# with subdirectories breaks every one of them.
#
# NO EXTERNAL DEPENDENCY. The scripts read PE exports with /usr/bin/perl,
# which macOS ships. /usr/bin/python3 is not Python -- it is one of 78 hard
# links to the xcrun dispatcher, and on a Mac without developer tools it opens
# a dialog and fails. A compiled helper is not an option either: downloaded
# binaries arrive quarantined and Gatekeeper stops them, text scripts do not.
#
# PROVENANCE IS NOT OPTIONAL. The manifest records the commit and says plainly
# whether the tree was clean and whether that commit is a released tag. An
# asset attached to a release must be buildable from that release; publishing
# one that is not is the quiet mismatch this project keeps removing.
#
# SPDX-License-Identifier: GPL-3.0-or-later

set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
REPO="$(cd "$HERE/.." && pwd)"
OUT="${1:-$REPO/build}"

command -v /usr/bin/perl >/dev/null || { echo "error: /usr/bin/perl is missing" >&2; exit 1; }

# Provenance, decided before anything is copied.
commit="$(git -C "$REPO" rev-parse --short HEAD)"
dirty=false
git -C "$REPO" diff --quiet && git -C "$REPO" diff --cached --quiet || dirty=true
tag="$(git -C "$REPO" describe --tags --exact-match 2>/dev/null || true)"
released=true
[ -n "$tag" ] || released=false
version="${tag:-$(git -C "$REPO" describe --tags 2>/dev/null || echo "0.0.0")}"

stage="$(mktemp -d)"
trap 'rm -rf "$stage"' EXIT

echo "[1/4] collecting what the installers say they need"
count=0
for f in "$REPO"/runtime/install-*.sh; do
  cp "$f" "$stage/"
  count=$((count + 1))
  # Every $HERE/<file> an installer names is a file it must find beside it.
  while read -r want; do
    [ -n "$want" ] || continue
    [ -f "$REPO/runtime/$want" ] || { echo "error: $(basename "$f") wants $want, which is not in runtime/" >&2; exit 1; }
    cp "$REPO/runtime/$want" "$stage/"
  done < <(grep -oE '\$HERE/[A-Za-z0-9._-]+' "$f" | sed 's|\$HERE/||' | sort -u)
done
echo "      $count installers, $(( $(ls "$stage" | wc -l) - count )) files they name"

echo "[2/4] refusing anything that still needs python"
if grep -l 'python3' "$stage"/*.sh >/dev/null 2>&1; then
  echo "error: these installers still call python3, which a clean Mac does not have:" >&2
  grep -l 'python3' "$stage"/*.sh | sed 's|.*/|       |' >&2
  exit 1
fi
echo "      none"

echo "[3/4] writing the manifest"
/usr/bin/perl - "$stage" "$version" "$commit" "$dirty" "$released" "$REPO" <<'PERL' > "$stage/manifest.json"
use strict; use warnings;
my ($stage, $version, $commit, $dirty, $released, $repo) = @ARGV;
my @games;
for my $f (sort glob("$repo/runtime/install-*.sh")) {
    open my $fh, '<', $f or next;
    my $s = do { local $/; <$fh> };
    my $grab = sub { my ($re) = @_; $s =~ /$re/m ? $1 : "" };
    my %seen; my @files = grep { !$seen{$_}++ } ($s =~ /\$HERE\/([A-Za-z0-9._-]+\.dll)/g);
    my $carrier = $grab->(qr/^LIVE="\$GAME\/(.+?)"/);
    my $kept    = $grab->(qr/^REAL="\$GAME\/(.+?)"/);
    $_ =~ s{.*/}{} for ($carrier, $kept);
    my $name = $f; $name =~ s{.*/}{};
    push @games, sprintf(
      qq({"script":"%s","exe":"%s","files":[%s],"carrier":"%s","keptAs":"%s","writesRegistry":%s}),
      $name, $grab->(qr/^EXE_NAME=['"](.+?)['"]/),
      join(",", map { qq("$_") } @files), $carrier, $kept,
      ($s =~ /reg\.exe/ ? "true" : "false"));
}
printf qq({\n  "schema": 1,\n  "version": "%s",\n  "commit": "%s",\n  "treeDirty": %s,\n  "fromReleasedTag": %s,\n  "note": "Generated by runtime/make-fixes-bundle.sh from the installers themselves. Do not edit.",\n  "games": [\n    %s\n  ]\n}\n),
  $version, $commit, $dirty, $released, join(",\n    ", @games);
PERL

echo "[4/4] packing"
mkdir -p "$OUT"
tarball="$OUT/fixes-$version.tar.gz"
# Reproducible enough to compare two builds of the same commit: sorted, no
# directory entry, no macOS extended attributes.
( cd "$stage" && COPYFILE_DISABLE=1 tar --no-xattrs -czf "$tarball" $(ls | sort) )
shasum -a 256 "$tarball" | sed "s|$OUT/||" > "$tarball.sha256"

echo
echo "      $tarball"
echo "      $(du -h "$tarball" | cut -f1), $(ls "$stage" | wc -l | tr -d ' ') files"
echo "      $(cat "$tarball.sha256")"
[ "$dirty" = true ] && echo "      WARNING: built from a dirty tree -- not publishable as-is" >&2
[ "$released" = false ] && echo "      WARNING: HEAD is not a tag -- do not attach this to a release" >&2
exit 0
