#!/usr/bin/env python3
"""
Generate the ID3D11VideoDevice / ID3D11VideoContext stub vtables from d3d11.h.

Between them the two interfaces have around 85 methods, and a vtable in the
wrong order is worse than none -- the game would call something other than
what it asked for. Reading the order out of the header removes that risk, and
the header is the same one the game was compiled against.

Every stub logs its own name and refuses. The point is not to implement video;
it is to find out which methods the game actually needs before deciding
whether implementing them is worth it.

    gen-video-stubs.py <d3d11.h> > video-stubs.h

SPDX-License-Identifier: GPL-3.0-or-later
"""

import re
import sys

# Methods that do not return an HRESULT. Handing back E_NOTIMPL as a count
# would claim two billion entries, which is a great deal worse than zero.
RETURNS_COUNT = {"GetVideoDecoderProfileCount"}

# Written by hand in mf-probe.c because a refusal is not a usable answer.
HAND_WRITTEN = {
    "ID3D11VideoDevice::CreateVideoProcessorEnumerator",
    "ID3D11VideoDevice::CreateVideoProcessor",
    "ID3D11VideoDevice::CreateVideoProcessorInputView",
    "ID3D11VideoDevice::CreateVideoProcessorOutputView",
    "ID3D11VideoProcessorEnumerator::CheckVideoProcessorFormat",
    "ID3D11VideoProcessorEnumerator::GetVideoProcessorCaps",
    "ID3D11VideoProcessorEnumerator::GetVideoProcessorContentDesc",
    "ID3D11VideoProcessorEnumerator::GetVideoProcessorRateConversionCaps",
    "ID3D11VideoProcessorInputView::GetResource",
    "ID3D11VideoProcessorOutputView::GetResource",
    "ID3D11VideoContext::VideoProcessorBlt",
}


def methods(header, vtbl):
    text = open(header).read()
    start = text.index(f"{vtbl}Vtbl")
    # The vtable struct ends at the closing brace of its typedef.
    end = text.index("\n} ", start)
    body = text[start:end]
    names = re.findall(r"\*(\w+)\)\(", body)
    if names[:3] != ["QueryInterface", "AddRef", "Release"]:
        raise SystemExit(f"{vtbl}: unexpected head {names[:3]}")
    return names


def emit(iface, prefix, names):
    print(f"/* ---- {iface}: {len(names)} methods ---- */")
    for i, name in enumerate(names[3:], start=3):
        if f"{iface}::{name}" in HAND_WRITTEN:
            continue
        zero = name in RETURNS_COUNT
        print(f"static ULONG_PTR WINAPI {prefix}_{i}(void *self, void *a, void *b, void *c,")
        print(f"                                     void *d, void *e, void *f)")
        print( "{")
        print( "    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;")
        print(f'    stub_called("{iface}::{name}");')
        print(f"    return {'0' if zero else '(ULONG_PTR)E_NOTIMPL'};")
        print( "}")
    print(f"\nstatic void *{prefix}_vtbl[] =")
    print( "{")
    print( "    stub_QueryInterface, stub_AddRef, stub_Release,")
    for i, name in enumerate(names[3:], start=3):
        full = f"{iface}::{name}"
        if full in HAND_WRITTEN:
            print(f"    {prefix}_{name},   /* hand-written */")
        else:
            print(f"    {prefix}_{i},")
    print( "};\n")


# The video processor is what converts the decoded NV12 into the BGRA texture
# the game draws. Everything needed to reach that blit gets a vtable.
INTERFACES = [
    ("ID3D11VideoDevice",                "vd"),
    ("ID3D11VideoContext",               "vc"),
    ("ID3D11VideoProcessorEnumerator",   "vpe"),
    ("ID3D11VideoProcessor",             "vp"),
    ("ID3D11VideoProcessorInputView",    "vpiv"),
    ("ID3D11VideoProcessorOutputView",   "vpov"),
]


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__.strip())
    header = sys.argv[1]
    print("/* Generated by gen-video-stubs.py from d3d11.h. Do not edit. */")
    print("/* SPDX-License-Identifier: GPL-3.0-or-later */\n")
    for iface, prefix in INTERFACES:
        emit(iface, prefix, methods(header, iface))


if __name__ == "__main__":
    main()
