#!/usr/bin/env python3
"""
Generate the ID3D11VideoDevice / ID3D11VideoContext stub vtables from d3d11.h.

Between them the two interfaces have around 85 methods, and a vtable in the
wrong order is worse than none -- the game would call something other than
what it asked for. Reading the order out of the header removes that risk, and
the header is the same one the game was compiled against.

Every stub logs its own name and refuses. The point is not to implement video;
it is to find out which methods the game actually needs before deciding
whether implementing them is worth it.

    gen-video-stubs.py <d3d11.h> > video-stubs.h

SPDX-License-Identifier: GPL-3.0-or-later
"""

import re
import sys

# Methods that do not return an HRESULT. Handing back E_NOTIMPL as a count
# would claim two billion entries, which is a great deal worse than zero.
RETURNS_COUNT = {"GetVideoDecoderProfileCount"}


def methods(header, vtbl):
    text = open(header).read()
    start = text.index(f"{vtbl}Vtbl")
    # The vtable struct ends at the closing brace of its typedef.
    end = text.index("\n} ", start)
    body = text[start:end]
    names = re.findall(r"\*(\w+)\)\(", body)
    if names[:3] != ["QueryInterface", "AddRef", "Release"]:
        raise SystemExit(f"{vtbl}: unexpected head {names[:3]}")
    return names


def emit(iface, prefix, names):
    print(f"/* ---- {iface}: {len(names)} methods ---- */")
    for i, name in enumerate(names[3:], start=3):
        zero = name in RETURNS_COUNT
        print(f"static ULONG_PTR WINAPI {prefix}_{i}(void *self, void *a, void *b, void *c,")
        print(f"                                     void *d, void *e, void *f)")
        print( "{")
        print( "    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;")
        print(f'    stub_called("{iface}::{name}");')
        print(f"    return {'0' if zero else '(ULONG_PTR)E_NOTIMPL'};")
        print( "}")
    print(f"\nstatic void *{prefix}_vtbl[] =")
    print( "{")
    print( "    stub_QueryInterface, stub_AddRef, stub_Release,")
    for i in range(3, len(names)):
        print(f"    {prefix}_{i},")
    print( "};\n")


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__.strip())
    header = sys.argv[1]
    print("/* Generated by gen-video-stubs.py from d3d11.h. Do not edit. */")
    print("/* SPDX-License-Identifier: GPL-3.0-or-later */\n")
    emit("ID3D11VideoDevice", "vd", methods(header, "ID3D11VideoDevice"))
    emit("ID3D11VideoContext", "vc", methods(header, "ID3D11VideoContext"))


if __name__ == "__main__":
    main()
