/* Generated by gen-video-stubs.py from d3d11.h. Do not edit. */
/* SPDX-License-Identifier: GPL-3.0-or-later */

/* ---- ID3D11VideoDevice: 20 methods ---- */
static ULONG_PTR WINAPI vd_3(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoDevice::CreateVideoDecoder");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vd_5(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoDevice::CreateAuthenticatedChannel");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vd_6(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoDevice::CreateCryptoSession");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vd_7(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoDevice::CreateVideoDecoderOutputView");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vd_11(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoDevice::GetVideoDecoderProfileCount");
    return 0;
}
static ULONG_PTR WINAPI vd_12(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoDevice::GetVideoDecoderProfile");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vd_13(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoDevice::CheckVideoDecoderFormat");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vd_14(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoDevice::GetVideoDecoderConfigCount");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vd_15(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoDevice::GetVideoDecoderConfig");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vd_16(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoDevice::GetContentProtectionCaps");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vd_17(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoDevice::CheckCryptoKeyExchange");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vd_18(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoDevice::SetPrivateData");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vd_19(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoDevice::SetPrivateDataInterface");
    return (ULONG_PTR)E_NOTIMPL;
}

static void *vd_vtbl[] =
{
    stub_QueryInterface, stub_AddRef, stub_Release,
    vd_3,
    vd_CreateVideoProcessor,   /* hand-written */
    vd_5,
    vd_6,
    vd_7,
    vd_CreateVideoProcessorInputView,   /* hand-written */
    vd_CreateVideoProcessorOutputView,   /* hand-written */
    vd_CreateVideoProcessorEnumerator,   /* hand-written */
    vd_11,
    vd_12,
    vd_13,
    vd_14,
    vd_15,
    vd_16,
    vd_17,
    vd_18,
    vd_19,
};

/* ---- ID3D11VideoContext: 65 methods ---- */
static ULONG_PTR WINAPI vc_3(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoContext::GetDevice");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vc_4(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoContext::GetPrivateData");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vc_5(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoContext::SetPrivateData");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vc_6(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoContext::SetPrivateDataInterface");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vc_7(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoContext::GetDecoderBuffer");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vc_8(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoContext::ReleaseDecoderBuffer");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vc_9(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoContext::DecoderBeginFrame");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vc_10(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoContext::DecoderEndFrame");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vc_11(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoContext::SubmitDecoderBuffers");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vc_12(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoContext::DecoderExtension");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vc_13(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoContext::VideoProcessorSetOutputTargetRect");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vc_14(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoContext::VideoProcessorSetOutputBackgroundColor");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vc_15(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoContext::VideoProcessorSetOutputColorSpace");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vc_16(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoContext::VideoProcessorSetOutputAlphaFillMode");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vc_17(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoContext::VideoProcessorSetOutputConstriction");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vc_18(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoContext::VideoProcessorSetOutputStereoMode");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vc_19(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoContext::VideoProcessorSetOutputExtension");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vc_20(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoContext::VideoProcessorGetOutputTargetRect");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vc_21(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoContext::VideoProcessorGetOutputBackgroundColor");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vc_22(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoContext::VideoProcessorGetOutputColorSpace");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vc_23(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoContext::VideoProcessorGetOutputAlphaFillMode");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vc_24(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoContext::VideoProcessorGetOutputConstriction");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vc_25(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoContext::VideoProcessorGetOutputStereoMode");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vc_26(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoContext::VideoProcessorGetOutputExtension");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vc_27(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoContext::VideoProcessorSetStreamFrameFormat");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vc_28(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoContext::VideoProcessorSetStreamColorSpace");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vc_29(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoContext::VideoProcessorSetStreamOutputRate");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vc_30(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoContext::VideoProcessorSetStreamSourceRect");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vc_31(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoContext::VideoProcessorSetStreamDestRect");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vc_32(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoContext::VideoProcessorSetStreamAlpha");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vc_33(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoContext::VideoProcessorSetStreamPalette");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vc_34(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoContext::VideoProcessorSetStreamPixelAspectRatio");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vc_35(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoContext::VideoProcessorSetStreamLumaKey");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vc_36(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoContext::VideoProcessorSetStreamStereoFormat");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vc_37(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoContext::VideoProcessorSetStreamAutoProcessingMode");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vc_38(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoContext::VideoProcessorSetStreamFilter");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vc_39(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoContext::VideoProcessorSetStreamExtension");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vc_40(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoContext::VideoProcessorGetStreamFrameFormat");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vc_41(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoContext::VideoProcessorGetStreamColorSpace");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vc_42(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoContext::VideoProcessorGetStreamOutputRate");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vc_43(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoContext::VideoProcessorGetStreamSourceRect");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vc_44(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoContext::VideoProcessorGetStreamDestRect");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vc_45(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoContext::VideoProcessorGetStreamAlpha");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vc_46(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoContext::VideoProcessorGetStreamPalette");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vc_47(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoContext::VideoProcessorGetStreamPixelAspectRatio");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vc_48(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoContext::VideoProcessorGetStreamLumaKey");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vc_49(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoContext::VideoProcessorGetStreamStereoFormat");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vc_50(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoContext::VideoProcessorGetStreamAutoProcessingMode");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vc_51(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoContext::VideoProcessorGetStreamFilter");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vc_52(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoContext::VideoProcessorGetStreamExtension");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vc_54(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoContext::NegotiateCryptoSessionKeyExchange");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vc_55(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoContext::EncryptionBlt");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vc_56(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoContext::DecryptionBlt");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vc_57(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoContext::StartSessionKeyRefresh");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vc_58(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoContext::FinishSessionKeyRefresh");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vc_59(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoContext::GetEncryptionBltKey");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vc_60(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoContext::NegotiateAuthenticatedChannelKeyExchange");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vc_61(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoContext::QueryAuthenticatedChannel");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vc_62(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoContext::ConfigureAuthenticatedChannel");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vc_63(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoContext::VideoProcessorSetStreamRotation");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vc_64(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoContext::VideoProcessorGetStreamRotation");
    return (ULONG_PTR)E_NOTIMPL;
}

static void *vc_vtbl[] =
{
    stub_QueryInterface, stub_AddRef, stub_Release,
    vc_3,
    vc_4,
    vc_5,
    vc_6,
    vc_7,
    vc_8,
    vc_9,
    vc_10,
    vc_11,
    vc_12,
    vc_13,
    vc_14,
    vc_15,
    vc_16,
    vc_17,
    vc_18,
    vc_19,
    vc_20,
    vc_21,
    vc_22,
    vc_23,
    vc_24,
    vc_25,
    vc_26,
    vc_27,
    vc_28,
    vc_29,
    vc_30,
    vc_31,
    vc_32,
    vc_33,
    vc_34,
    vc_35,
    vc_36,
    vc_37,
    vc_38,
    vc_39,
    vc_40,
    vc_41,
    vc_42,
    vc_43,
    vc_44,
    vc_45,
    vc_46,
    vc_47,
    vc_48,
    vc_49,
    vc_50,
    vc_51,
    vc_52,
    vc_VideoProcessorBlt,   /* hand-written */
    vc_54,
    vc_55,
    vc_56,
    vc_57,
    vc_58,
    vc_59,
    vc_60,
    vc_61,
    vc_62,
    vc_63,
    vc_64,
};

/* ---- ID3D11VideoProcessorEnumerator: 13 methods ---- */
static ULONG_PTR WINAPI vpe_3(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoProcessorEnumerator::GetDevice");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vpe_4(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoProcessorEnumerator::GetPrivateData");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vpe_5(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoProcessorEnumerator::SetPrivateData");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vpe_6(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoProcessorEnumerator::SetPrivateDataInterface");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vpe_11(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoProcessorEnumerator::GetVideoProcessorCustomRate");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vpe_12(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoProcessorEnumerator::GetVideoProcessorFilterRange");
    return (ULONG_PTR)E_NOTIMPL;
}

static void *vpe_vtbl[] =
{
    stub_QueryInterface, stub_AddRef, stub_Release,
    vpe_3,
    vpe_4,
    vpe_5,
    vpe_6,
    vpe_GetVideoProcessorContentDesc,   /* hand-written */
    vpe_CheckVideoProcessorFormat,   /* hand-written */
    vpe_GetVideoProcessorCaps,   /* hand-written */
    vpe_GetVideoProcessorRateConversionCaps,   /* hand-written */
    vpe_11,
    vpe_12,
};

/* ---- ID3D11VideoProcessor: 9 methods ---- */
static ULONG_PTR WINAPI vp_3(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoProcessor::GetDevice");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vp_4(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoProcessor::GetPrivateData");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vp_5(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoProcessor::SetPrivateData");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vp_6(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoProcessor::SetPrivateDataInterface");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vp_7(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoProcessor::GetContentDesc");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vp_8(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoProcessor::GetRateConversionCaps");
    return (ULONG_PTR)E_NOTIMPL;
}

static void *vp_vtbl[] =
{
    stub_QueryInterface, stub_AddRef, stub_Release,
    vp_3,
    vp_4,
    vp_5,
    vp_6,
    vp_7,
    vp_8,
};

/* ---- ID3D11VideoProcessorInputView: 9 methods ---- */
static ULONG_PTR WINAPI vpiv_3(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoProcessorInputView::GetDevice");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vpiv_4(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoProcessorInputView::GetPrivateData");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vpiv_5(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoProcessorInputView::SetPrivateData");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vpiv_6(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoProcessorInputView::SetPrivateDataInterface");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vpiv_8(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoProcessorInputView::GetDesc");
    return (ULONG_PTR)E_NOTIMPL;
}

static void *vpiv_vtbl[] =
{
    stub_QueryInterface, stub_AddRef, stub_Release,
    vpiv_3,
    vpiv_4,
    vpiv_5,
    vpiv_6,
    vpiv_GetResource,   /* hand-written */
    vpiv_8,
};

/* ---- ID3D11VideoProcessorOutputView: 9 methods ---- */
static ULONG_PTR WINAPI vpov_3(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoProcessorOutputView::GetDevice");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vpov_4(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoProcessorOutputView::GetPrivateData");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vpov_5(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoProcessorOutputView::SetPrivateData");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vpov_6(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoProcessorOutputView::SetPrivateDataInterface");
    return (ULONG_PTR)E_NOTIMPL;
}
static ULONG_PTR WINAPI vpov_8(void *self, void *a, void *b, void *c,
                                     void *d, void *e, void *f)
{
    (void)self; (void)a; (void)b; (void)c; (void)d; (void)e; (void)f;
    stub_called("ID3D11VideoProcessorOutputView::GetDesc");
    return (ULONG_PTR)E_NOTIMPL;
}

static void *vpov_vtbl[] =
{
    stub_QueryInterface, stub_AddRef, stub_Release,
    vpov_3,
    vpov_4,
    vpov_5,
    vpov_6,
    vpov_GetResource,   /* hand-written */
    vpov_8,
};

